export const fitnessScoreLb = {
  rankList: [
    {
      code: 'GEOR',
      name: 'George',
      rank: 1,
      rankChange: 0,
      totalScore: 8.7,
    },
    {
      code: 'NISH',
      name: 'Nishiket',
      rank: 2,
      rankChange: 0,
      totalScore: 8.2,
    },
    {
      code: 'ABH',
      name: 'Abhay',
      rank: 3,
      rankChange: 0,
      totalScore: 8.1,
    },
    {
      code: 'RISH',
      name: 'Rishi Solanki',
      rank: 4,
      rankChange: 0,
      totalScore: 8.1,
    },
    {
      code: 'ESHW',
      name: 'Eshwar',
      rank: 5,
      rankChange: 0,
      totalScore: 8,
    },
    {
      code: 'KART',
      name: 'Kartik',
      rank: 6,
      rankChange: 0,
      totalScore: 7.9,
    },
    {
      code: 'AJAY',
      name: 'Ajay',
      rank: 7,
      rankChange: 0,
      totalScore: 7.8,
    },
    {
      code: 'JAN',
      name: 'Jannis',
      rank: 8,
      rankChange: 0,
      totalScore: 7.5,
    },
    {
      code: 'ADIT',
      name: 'Aditya',
      rank: 9,
      rankChange: 0,
      totalScore: 7.5,
    },
    {
      code: 'LAV',
      name: 'Laveen',
      rank: 10,
      rankChange: 0,
      totalScore: 7.4,
    },
    {
      code: 'PRIYE',
      name: 'Priyesh',
      rank: 11,
      rankChange: 0,
      totalScore: 7.1,
    },
    {
      code: 'ARYA',
      name: 'Arya',
      rank: 12,
      rankChange: 0,
      totalScore: 7,
    },
    {
      code: 'JAIM',
      name: 'Jaimy',
      rank: 13,
      rankChange: 0,
      totalScore: 6.7,
    },
    {
      code: 'IVDU',
      name: 'Ivy Dutta',
      rank: 14,
      rankChange: 0,
      totalScore: 6.5,
    },
    {
      code: 'NEGA',
      name: 'Neetu Gaur',
      rank: 15,
      rankChange: 0,
      totalScore: 6.3,
    },
    {
      code: 'DHRI',
      name: 'Dhriti',
      rank: 16,
      rankChange: 0,
      totalScore: 6.1,
    },
    {
      code: 'SANJ',
      name: 'Sanjeet',
      rank: 17,
      rankChange: 0,
      totalScore: 6,
    },
    {
      code: 'VIV',
      name: 'Vivian',
      rank: 18,
      rankChange: 0,
      totalScore: 6,
    },
    {
      code: 'PAJA',
      name: 'Palak',
      rank: 19,
      rankChange: 0,
      totalScore: 5.8,
    },
    {
      code: 'TAVA',
      name: 'Tanvi Vartak',
      rank: 20,
      rankChange: 0,
      totalScore: 5.7,
    },
    {
      code: 'KU',
      name: 'Kunal',
      rank: 21,
      rankChange: 0,
      totalScore: 5.6,
    },
    {
      code: 'AKAN',
      name: 'Akanksha Singla',
      rank: 22,
      rankChange: 0,
      totalScore: 5.6,
    },
    {
      code: 'PIA',
      name: 'Pia',
      rank: 23,
      rankChange: 0,
      totalScore: 5.6,
    },
    {
      code: 'PAGA',
      name: 'Palak Aggarwal',
      rank: 24,
      rankChange: 0,
      totalScore: 5.6,
    },
    {
      code: 'NE',
      name: 'Neeraja',
      rank: 25,
      rankChange: 0,
      totalScore: 5.6,
    },
    {
      code: 'MAD',
      name: 'Madhav',
      rank: 26,
      rankChange: 0,
      totalScore: 5.5,
    },
    {
      code: 'VINE',
      name: 'Vineet',
      rank: 27,
      rankChange: 0,
      totalScore: 5.5,
    },
    {
      code: 'AADU',
      name: 'Aakanksha Dua',
      rank: 28,
      rankChange: 0,
      totalScore: 5.5,
    },
    {
      code: 'HARS',
      name: 'Harshith',
      rank: 29,
      rankChange: 0,
      totalScore: 5.4,
    },
    {
      code: 'CHAN',
      name: 'Chandni',
      rank: 30,
      rankChange: 0,
      totalScore: 5.4,
    },
    {
      code: 'DIKS',
      name: 'Diksha',
      rank: 31,
      rankChange: 0,
      totalScore: 5.3,
    },
    {
      code: 'SANC',
      name: 'Sanchit',
      rank: 32,
      rankChange: 0,
      totalScore: 5.2,
    },
    {
      code: 'SISH',
      name: 'Siddhi Shrivastava',
      rank: 33,
      rankChange: 0,
      totalScore: 5.1,
    },
    {
      code: 'NATAL',
      name: 'Natalie',
      rank: 34,
      rankChange: 0,
      totalScore: 4.8,
    },
    {
      code: 'SANI',
      name: 'Sanika',
      rank: 35,
      rankChange: 0,
      totalScore: 4.8,
    },
    {
      code: 'NAMA',
      name: 'Natasha Mahindra',
      rank: 36,
      rankChange: 0,
      totalScore: 4.8,
    },
    {
      code: 'HIM',
      name: 'Himaneesh',
      rank: 37,
      rankChange: 0,
      totalScore: 4.7,
    },
    {
      code: 'DARJ',
      name: 'Darja',
      rank: 38,
      rankChange: 0,
      totalScore: 4.7,
    },
    {
      code: 'ROSH',
      name: 'Rohaan Shah',
      rank: 39,
      rankChange: 0,
      totalScore: 4.7,
    },
    {
      code: 'NIHI',
      name: 'Nihit',
      rank: 40,
      rankChange: 0,
      totalScore: 4.6,
    },
    {
      code: 'KANC',
      name: 'Kanchi',
      rank: 41,
      rankChange: 0,
      totalScore: 4.6,
    },
    {
      code: 'RAKS',
      name: 'Raksha',
      rank: 42,
      rankChange: 0,
      totalScore: 4.4,
    },
    {
      code: 'KRUT',
      name: 'Kruttika',
      rank: 43,
      rankChange: 0,
      totalScore: 4.3,
    },
    {
      code: 'KOKA',
      name: 'Komal Karani',
      rank: 44,
      rankChange: 0,
      totalScore: 4.3,
    },
    {
      code: 'VAGU',
      name: 'Vasudha Gupta',
      rank: 45,
      rankChange: 0,
      totalScore: 4.1,
    },
    {
      code: 'AKSH',
      name: 'Akshay',
      rank: 46,
      rankChange: 0,
      totalScore: 4,
    },
    {
      code: 'SANIY',
      name: 'Saniya',
      rank: 47,
      rankChange: 0,
      totalScore: 3.4,
    },
    {
      code: 'MOH',
      name: 'Mohit',
      rank: 48,
      rankChange: 0,
      totalScore: 3.4,
    },
    {
      code: 'PUP7629',
      name: 'Pushpak P',
      rank: 49,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'PST231762',
      name: 'Psk t23',
      rank: 50,
      rankChange: 50,
      totalScore: 1,
    },
    {
      code: 'PUP7944',
      name: 'Pushpak P',
      rank: 51,
      rankChange: 51,
      totalScore: 1,
    },
    {
      code: 'PST239787',
      name: 'Psk t23',
      rank: 52,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'PUP6737',
      name: 'Pushpak P',
      rank: 53,
      rankChange: 53,
      totalScore: 1,
    },
    {
      code: 'PST235314',
      name: 'Psk t23',
      rank: 54,
      rankChange: 54,
      totalScore: 1,
    },
    {
      code: 'PUP4077',
      name: 'Pushpak P',
      rank: 55,
      rankChange: 55,
      totalScore: 1,
    },
    {
      code: 'PS3207',
      name: 'Psk  t23',
      rank: 56,
      rankChange: 56,
      totalScore: 1,
    },
    {
      code: 'PUP5060',
      name: 'Pushpak P',
      rank: 57,
      rankChange: 57,
      totalScore: 1,
    },
    {
      code: 'MOMANG9378',
      name: 'Mohit Mangal',
      rank: 58,
      rankChange: 58,
      totalScore: 1,
    },
    {
      code: 'PRAT',
      name: 'Pratham',
      rank: 59,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'LAKS',
      name: 'Lakshvir',
      rank: 60,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'RAMA',
      name: 'Raman',
      rank: 61,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SONA',
      name: 'Sonali',
      rank: 62,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'NAMI',
      name: 'Namisha',
      rank: 63,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ROHA',
      name: 'Rohan Sarda',
      rank: 64,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'DHRU',
      name: 'Dhruv',
      rank: 65,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'JAY',
      name: 'Jay',
      rank: 66,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'TARU',
      name: 'Tarun',
      rank: 67,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'PRIT',
      name: 'Pritika',
      rank: 68,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'AMAN',
      name: 'Aman',
      rank: 69,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'APOO',
      name: 'Apoorva',
      rank: 70,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ANUS',
      name: 'Anushka',
      rank: 71,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'MIHI',
      name: 'Mihir',
      rank: 72,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'AKSHA',
      name: 'Akshat',
      rank: 73,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'KAJA',
      name: 'Kajal',
      rank: 74,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'NIKH',
      name: 'Nikhil',
      rank: 75,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ARJU',
      name: 'Arjun',
      rank: 76,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SWAR',
      name: 'Swaraj',
      rank: 77,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'MICH',
      name: 'Michael',
      rank: 78,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'PREE',
      name: 'Preetal',
      rank: 79,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ISHI',
      name: 'Ishita',
      rank: 80,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'KARTK',
      name: 'Kartik K.',
      rank: 81,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'MOJO',
      name: 'Mojo',
      rank: 82,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SIBA',
      name: 'Siddharth Bapna',
      rank: 83,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'DIVY',
      name: 'Divya',
      rank: 84,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SUKA',
      name: 'Sukanya W',
      rank: 85,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'AYUD',
      name: 'Ayudh',
      rank: 86,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ABDU',
      name: 'Abdul',
      rank: 87,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'VIDH',
      name: 'Vidhi',
      rank: 88,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ASHO',
      name: 'Ashok',
      rank: 89,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SHAR',
      name: 'Shardul',
      rank: 90,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'TANM',
      name: 'Tanmay',
      rank: 91,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'HIRE',
      name: 'Hiren',
      rank: 92,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ANAN',
      name: 'Ananya',
      rank: 93,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SANGO',
      name: 'Sangeeta',
      rank: 94,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'DURG',
      name: 'Durga',
      rank: 95,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'KATI',
      name: 'Katia',
      rank: 96,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'VANI',
      name: 'Vanil',
      rank: 97,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'MEGH',
      name: 'Megha',
      rank: 98,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'DCT',
      name: 'DC Tarun',
      rank: 99,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'PRI',
      name: 'Priyansha',
      rank: 100,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SOWM',
      name: 'Sowmya',
      rank: 101,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'MEG',
      name: 'Megh',
      rank: 102,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'DEVE',
      name: 'Devet',
      rank: 103,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'ABHI',
      name: 'Abhimanyu',
      rank: 104,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'RUFY',
      name: 'Rufy',
      rank: 105,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SHOB',
      name: 'Shobhit',
      rank: 106,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'RUHE',
      name: 'Ruhee',
      rank: 107,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SNEH',
      name: 'Sneha',
      rank: 108,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'PRAN',
      name: 'Pranav',
      rank: 109,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'SAN',
      name: 'Sania',
      rank: 110,
      rankChange: 0,
      totalScore: 1,
    },
    {
      code: 'NOOR',
      name: 'Noor',
      rank: 111,
      rankChange: 0,
      totalScore: 1,
    },
  ],
  total: 111,
};

export const consistencyLeaderboard = {
  rankList: [
    {
      name: 'Pranav',
      code: 'PRAN',
      workout: 7,
      rank: 1,
      rankChange: 0,
    },
    {
      name: 'Aakanksha Dua',
      code: 'AADU',
      workout: 5,
      rank: 2,
      rankChange: 0,
    },
    {
      name: 'Kunal',
      code: 'KU',
      workout: 4,
      rank: 3,
      rankChange: 0,
    },
    {
      name: 'Abdul',
      code: 'ABDU',
      workout: 0,
      rank: 4,
      rankChange: 0,
    },
    {
      name: 'Abhay',
      code: 'ABH',
      workout: 0,
      rank: 5,
      rankChange: 0,
    },
    {
      name: 'Aditya',
      code: 'ADIT',
      workout: 0,
      rank: 6,
      rankChange: 0,
    },
    {
      name: 'Ajay',
      code: 'AJAY',
      workout: 0,
      rank: 7,
      rankChange: 0,
    },
    {
      name: 'Akanksha Singla',
      code: 'AKAN',
      workout: 0,
      rank: 8,
      rankChange: 0,
    },
    {
      name: 'Akash Agrawal',
      code: 'AKAS',
      workout: 0,
      rank: 9,
      rankChange: 0,
    },
    {
      name: 'Akshat',
      code: 'AKSHA',
      workout: 0,
      rank: 10,
      rankChange: 0,
    },
    {
      name: 'Akshay',
      code: 'AKSH',
      workout: 0,
      rank: 11,
      rankChange: 0,
    },
    {
      name: 'Ali',
      code: 'ALI',
      workout: 0,
      rank: 12,
      rankChange: 0,
    },
    {
      name: 'Aman',
      code: 'AMAN',
      workout: 0,
      rank: 13,
      rankChange: 0,
    },
    {
      name: 'Ananya',
      code: 'ANAN',
      workout: 0,
      rank: 14,
      rankChange: 0,
    },
    {
      name: 'Anushka',
      code: 'ANUS',
      workout: 0,
      rank: 15,
      rankChange: 0,
    },
    {
      name: 'Apoorva',
      code: 'APOO',
      workout: 0,
      rank: 16,
      rankChange: 0,
    },
    {
      name: 'Arya',
      code: 'ARYA',
      workout: 0,
      rank: 17,
      rankChange: 0,
    },
    {
      name: 'Ashok',
      code: 'ASHO',
      workout: 0,
      rank: 18,
      rankChange: 0,
    },
    {
      name: 'Aviraj',
      code: 'AVIR',
      workout: 0,
      rank: 19,
      rankChange: 0,
    },
    {
      name: 'Ayudh',
      code: 'AYUD',
      workout: 0,
      rank: 20,
      rankChange: 0,
    },
    {
      name: 'Chandni',
      code: 'CHAN',
      workout: 0,
      rank: 21,
      rankChange: 0,
    },
    {
      name: 'Chirantan',
      code: 'CHIR',
      workout: 0,
      rank: 22,
      rankChange: 0,
    },
    {
      name: 'Dhriti',
      code: 'DHRI',
      workout: 0,
      rank: 23,
      rankChange: 0,
    },
    {
      name: 'Dhruv',
      code: 'DHRU',
      workout: 0,
      rank: 24,
      rankChange: 0,
    },
    {
      name: 'Diksha',
      code: 'DIKS',
      workout: 0,
      rank: 25,
      rankChange: 0,
    },
    {
      name: 'Div Shah',
      code: 'DIVS',
      workout: 0,
      rank: 26,
      rankChange: 0,
    },
    {
      name: 'Durga',
      code: 'DURG',
      workout: 0,
      rank: 27,
      rankChange: 0,
    },
    {
      name: 'Eshwar',
      code: 'ESHW',
      workout: 0,
      rank: 28,
      rankChange: 0,
    },
    {
      name: 'George',
      code: 'GEOR',
      workout: 0,
      rank: 29,
      rankChange: 0,
    },
    {
      name: 'Harsh',
      code: 'HARSH',
      workout: 0,
      rank: 30,
      rankChange: 0,
    },
    {
      name: 'Harshith',
      code: 'HARS',
      workout: 0,
      rank: 31,
      rankChange: 0,
    },
    {
      name: 'Himaneesh',
      code: 'HIM',
      workout: 0,
      rank: 32,
      rankChange: 0,
    },
    {
      name: 'Indrani',
      code: 'INDR',
      workout: 0,
      rank: 33,
      rankChange: 0,
    },
    {
      name: 'Jaimy',
      code: 'JAIM',
      workout: 0,
      rank: 34,
      rankChange: 0,
    },
    {
      name: 'Jannis',
      code: 'JAN',
      workout: 0,
      rank: 35,
      rankChange: 0,
    },
    {
      name: 'Jay',
      code: 'JAY',
      workout: 0,
      rank: 36,
      rankChange: 0,
    },
    {
      name: 'Kajal',
      code: 'KAJA',
      workout: 0,
      rank: 37,
      rankChange: 0,
    },
    {
      name: 'Kanchi',
      code: 'KANC',
      workout: 0,
      rank: 38,
      rankChange: 0,
    },
    {
      name: 'Kartik',
      code: 'KART',
      workout: 0,
      rank: 39,
      rankChange: 0,
    },
    {
      name: 'Kartik K.',
      code: 'KARTK',
      workout: 0,
      rank: 40,
      rankChange: 0,
    },
    {
      name: 'Komal',
      code: 'KOKA',
      workout: 0,
      rank: 41,
      rankChange: 0,
    },
    {
      name: 'Kruttika',
      code: 'KRUT',
      workout: 0,
      rank: 42,
      rankChange: 0,
    },
    {
      name: 'Lakshvir',
      code: 'LAKS',
      workout: 0,
      rank: 43,
      rankChange: 0,
    },
    {
      name: 'Madhav',
      code: 'MAD',
      workout: 0,
      rank: 44,
      rankChange: 0,
    },
    {
      name: 'Manthan',
      code: 'MANT',
      workout: 0,
      rank: 45,
      rankChange: 0,
    },
    {
      name: 'Mihir',
      code: 'MIHI',
      workout: 0,
      rank: 46,
      rankChange: 0,
    },
    {
      name: 'Mohit Gupta',
      code: 'MOHG',
      workout: 0,
      rank: 47,
      rankChange: 0,
    },
    {
      name: 'Mojo',
      code: 'MOJO',
      workout: 0,
      rank: 48,
      rankChange: 0,
    },
    {
      name: 'Namisha',
      code: 'NAMI',
      workout: 0,
      rank: 49,
      rankChange: 0,
    },
    {
      name: 'Natalie',
      code: 'NATAL',
      workout: 0,
      rank: 50,
      rankChange: 0,
    },
    {
      name: 'Neetu Gaur',
      code: 'NEGA',
      workout: 0,
      rank: 51,
      rankChange: 0,
    },
    {
      name: 'Nikita',
      code: 'NIKI',
      workout: 0,
      rank: 52,
      rankChange: 0,
    },
    {
      name: 'Nirav',
      code: 'NIRA',
      workout: 0,
      rank: 53,
      rankChange: 0,
    },
    {
      name: 'Nishiket',
      code: 'NISH',
      workout: 0,
      rank: 54,
      rankChange: 0,
    },
    {
      name: 'Palak',
      code: 'PAJA',
      workout: 0,
      rank: 55,
      rankChange: 0,
    },
    {
      name: 'Pratham',
      code: 'PRAT',
      workout: 0,
      rank: 56,
      rankChange: 0,
    },
    {
      name: 'Pritika',
      code: 'PRIT',
      workout: 0,
      rank: 57,
      rankChange: 0,
    },
    {
      name: 'Priyesh',
      code: 'PRIYE',
      workout: 0,
      rank: 58,
      rankChange: 0,
    },
    {
      name: 'Psk t23',
      code: 'PST239787',
      workout: 0,
      rank: 59,
      rankChange: 0,
    },
    {
      name: 'Pushpak P',
      code: 'PUP7629',
      workout: 0,
      rank: 60,
      rankChange: 0,
    },
    {
      name: 'Raksha',
      code: 'RAKS',
      workout: 0,
      rank: 61,
      rankChange: 0,
    },
    {
      name: 'Raman',
      code: 'RAMA',
      workout: 0,
      rank: 62,
      rankChange: 0,
    },
    {
      name: 'Rishi',
      code: 'RISHI',
      workout: 0,
      rank: 63,
      rankChange: 0,
    },
    {
      name: 'Rishi Sharma',
      code: 'RISHSH',
      workout: 0,
      rank: 64,
      rankChange: 0,
    },
    {
      name: 'Rishika',
      code: 'RISHIK',
      workout: 0,
      rank: 65,
      rankChange: 0,
    },
    {
      name: 'Rohaan Shah',
      code: 'ROSH',
      workout: 0,
      rank: 66,
      rankChange: 0,
    },
    {
      name: 'Rohan Sarda',
      code: 'ROHA',
      workout: 0,
      rank: 67,
      rankChange: 0,
    },
    {
      name: 'Rufy',
      code: 'RUFY',
      workout: 0,
      rank: 68,
      rankChange: 0,
    },
    {
      name: 'Sachneet',
      code: 'SACH',
      workout: 0,
      rank: 69,
      rankChange: 0,
    },
    {
      name: 'Sahil',
      code: 'SAHI',
      workout: 0,
      rank: 70,
      rankChange: 0,
    },
    {
      name: 'Sahil Sharma',
      code: 'SAHISH',
      workout: 0,
      rank: 71,
      rankChange: 0,
    },
    {
      name: 'Samarth',
      code: 'SAMA',
      workout: 0,
      rank: 72,
      rankChange: 0,
    },
    {
      name: 'Sameeksha',
      code: 'SAME',
      workout: 0,
      rank: 73,
      rankChange: 0,
    },
    {
      name: 'Samresh',
      code: 'SAMR',
      workout: 0,
      rank: 74,
      rankChange: 0,
    },
    {
      name: 'Sanchit',
      code: 'SANC',
      workout: 0,
      rank: 75,
      rankChange: 0,
    },
    {
      name: 'Sanika',
      code: 'SANI',
      workout: 0,
      rank: 76,
      rankChange: 0,
    },
    {
      name: 'Saniya',
      code: 'SANIY',
      workout: 0,
      rank: 77,
      rankChange: 0,
    },
    {
      name: 'Sanjeet',
      code: 'SANJ',
      workout: 0,
      rank: 78,
      rankChange: 0,
    },
    {
      name: 'Sayantoni',
      code: 'SAYA',
      workout: 0,
      rank: 79,
      rankChange: 0,
    },
    {
      name: 'Shobhit',
      code: 'SHOB',
      workout: 0,
      rank: 80,
      rankChange: 0,
    },
    {
      name: 'Shriram',
      code: 'SHRI',
      workout: 0,
      rank: 81,
      rankChange: 0,
    },
    {
      name: 'Sonali',
      code: 'SONA',
      workout: 0,
      rank: 82,
      rankChange: 0,
    },
    {
      name: 'Sowmya',
      code: 'SOWM',
      workout: 0,
      rank: 83,
      rankChange: 0,
    },
    {
      name: 'Srishti',
      code: 'SRIS',
      workout: 0,
      rank: 84,
      rankChange: 0,
    },
    {
      name: 'Suma Ganesh',
      code: 'SUMA',
      workout: 0,
      rank: 85,
      rankChange: 0,
    },
    {
      name: 'Tanishq',
      code: 'TANIS',
      workout: 0,
      rank: 86,
      rankChange: 0,
    },
    {
      name: 'Tanmay',
      code: 'TANM',
      workout: 0,
      rank: 87,
      rankChange: 0,
    },
    {
      name: 'Tanmay Shah',
      code: 'TANS',
      workout: 0,
      rank: 88,
      rankChange: 0,
    },
    {
      name: 'Treisha',
      code: 'TREI',
      workout: 0,
      rank: 89,
      rankChange: 0,
    },
    {
      name: 'Vineet',
      code: 'VINE',
      workout: 0,
      rank: 90,
      rankChange: 0,
    },
    {
      name: 'Vivian',
      code: 'VIV',
      workout: 0,
      rank: 91,
      rankChange: 0,
    },
    {
      name: 'Vrinda',
      code: 'VRIN',
      workout: 0,
      rank: 92,
      rankChange: 0,
    },
  ],
  total: 92,
};

